### ISSUE TITLE
[Server] Exception when client disconnects

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#151]
If the client disconnects we get the following exception:

```
Exception in thread "Thread-25815" java.util.ConcurrentModificationException
	at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:386)
	at java.util.AbstractList$Itr.next(AbstractList.java:355)
	at network.MediaStreaming$1.run(MediaStreaming.java:77)
	at java.lang.Thread.run(Thread.java:745)
```
We have to safely remove the disconnected client from the list in order to avoid such exceptions.

**Comment by trylimits** [comment]
Above commit fixes this issue by just handling this exception, i.e. completely dropping the current frame. Clean solution would be to use a concurrent list or something to store the clients.
