### ISSUE TITLE
[Server] Exception when removing clients due to inactivity

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#54]
If a client is removed due to inactivity the server throws the following exception:

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = Timer-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:210)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:393)
	at javafx.scene.Scene.addToDirtyList(Scene.java:529)
	at javafx.scene.Node.addToSceneDirtyList(Node.java:417)
	at javafx.scene.Node.impl_markDirty(Node.java:408)
	at javafx.scene.Node.notifyParentsOfInvalidatedCSS(Node.java:8664)
	at javafx.scene.Node.requestCssStateTransition(Node.java:8594)
	at javafx.scene.Node.pseudoClassStateChanged(Node.java:8635)
	at javafx.scene.Node$10.invalidated(Node.java:1606)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:143)
	at javafx.scene.Node.setDisabled(Node.java:1589)
	at javafx.scene.Node.updateDisabled(Node.java:1631)
	at javafx.scene.Node.access$500(Node.java:376)
	at javafx.scene.Node$MiscProperties$8.invalidated(Node.java:6480)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.access$000(BooleanPropertyBase.java:49)
	at javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:243)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.binding.BooleanBinding.invalidate(BooleanBinding.java:176)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:339)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
	at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:102)
	at javafx.scene.control.MultipleSelectionModelBase$1.invalidated(MultipleSelectionModelBase.java:70)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyIntegerWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:176)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:142)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:146)
	at javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:68)
	at javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateSelectedIndex(TableView.java:2595)
	at javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(TableView.java:2424)
	at javafx.scene.control.TableView$TableViewArrayListSelectionModel$7.onChanged(TableView.java:1937)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:315)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:72)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:183)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:171)
	at controllers.ClientController.removeClient(ClientController.java:64)
	at controllers.ClientController$1.run(ClientController.java:49)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by trylimits** [comment]
Fixed in above commit.
